AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  SAM Template for the OSRS Cache Parser

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    Environment:
      Variables:
        CACHE_BUCKET_NAME: "cache.api.2007scape.tools"

Resources:
  CacheParserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CacheParser
      Handler: cacheparser.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: arn:aws:iam::226176173674:role/CacheParser
      Events:
        TopicTrigger:
          Type: SNS
          Properties:
            Region: us-west-2
            Topic: arn:aws:sns:us-west-2:226176173674:cache-api-2007scape-tools

Outputs:
  CacheParserFunction:
    Description: "Cache Downloader Lambda Function ARN"
    Value: !GetAtt CacheParserFunction.Arn
